version: '3'

services:
  nginx:
    image: "nginx:1.15.2"
    ports:
      - "9527:9527"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
